# 项目全局配置

#需要调整小地图和大地图坐标
#大地图坐标为room_calutil.get_cur_room_index()
#其中818(x1) 404(y1)为大地图左上角坐标点,1507(x2) 712(y2)为大地图右下角坐标点，689为x2-x1=w，308为y2-y1=h
#  xy = rect_slice_index(Rect(818, 404, 689, 308), Size((6, 3)), point)

#小地图:
#其中2120,144为小地图在手机上的坐标点
#game_action.get_cur_room_index(),self.ctrl.click(2120, 144)


#是否在pc展示手机画面
scrcpy_show_window: False
#地图识别模式1:小地图识别，2:箭头识别
map_distinguish: 2
#debug功能:是否在本地保存小地图识别图像,1:保存，2:不保存
map_img_save: 2

#adb无线投屏，device_wifi_enable是否启用：1启动，2禁用。device_ip设备的IP地址
device_wifi_enable: 1
device_ip: 192.168.137.175:43291

# 链接的设备名或ip端口
#device: adb-24ed1083-yGX7n1._adb-tls-connect._tcp.
device: 24ed1083

# 当前的角色
cur_role: axiulou
#cur_role: naima
attack_distance: 600 # 攻击距离一般600够了

# 支持的所有角色，配置对应的配置文件路径
role_config:
  # 剑魂
  - role_name: jianhun
    path: jianhun.yaml
  # 阿修罗
  - role_name: axiulou
    path: axiulou.yaml
  # 红眼
  - role_name: hongyan
    path: hongyan.yaml
  # 大枪
  - role_name: daqiang
    path: daqiang.yaml
  # 奶妈
  - role_name: naima
    path: naima.yaml


# 技能与方向坐标点配置
coordinates:
  wheel_center: [398, 815] # 方向轮盘的中心点
  wheel_radius: 125 # 方向轮盘的半径 比实际的半径要小一点
  attack: [2050, 920] # 攻击按钮的坐标
  skill_d: [1447, 963] # 底部左边两个技能 d f
  skill_f: [1618, 973]
  skill_1: [1754, 957] # 按照王者的技能顺序 1 2 3 4 5
  skill_2: [1809, 806]
  skill_3: [1947, 675]
  skill_4: [2088, 650]
  skill_5: [2090, 484]
  skill_t: [1902, 985] # 后跳技能
  skill_y: [2135, 784] # 原地跳技能
  skill_q: [1780, 348] # 上方4个技能 q w e r
  skill_w: [1891, 348]
  skill_e: [1992, 348]
  skill_r: [2104, 348]
  skill_swip_center: [1934, 525] # 滑动技能的中心点


# 横向版的技能配置
#coordinates:
#  wheel_center: [460, 850] # 方向轮盘的中心点
#  wheel_radius: 125 # 方向轮盘的半径 比实际的半径要小一点
#  attack: [1945, 955] # 攻击按钮的坐标
#  skill_d: [1416, 840] # 底部左边两个技能 d f
#  skill_f: [1345, 961]
#  skill_1: [1645, 963] # 按照王者的技能顺序 1 2 3 4 5
#  skill_2: [1715, 840]
#  skill_3: [1861, 840]
#  skill_4: [1566, 840]
#  skill_5: [1500, 970]
#  skill_t: [1792, 959] # 后跳技能
#  skill_y: [2026, 836] # 原地跳技能
#  skill_q: [818, 962] # 上方4个技能 q w e r
#  skill_w: [928, 959]
#  skill_e: [1035, 958]
#  skill_r: [1145, 961]
#  skill_swip_center: [1950, 713] # 滑动技能的中心点